### ISSUE TITLE
Line number column overly indented

### ISSUE THREAD

**Issue by atmoio** [standardnotes/code-pro#3]
Excessive white space before the line number. The number should be closer to the left edge.
<img width="863" alt="Screen Shot 2021-01-13 at 9 20 03 AM" src="https://user-images.githubusercontent.com/3277844/104471515-9215a900-5580-11eb-978d-843fdceae4e1.png">

**Comment by theodorechu** [comment]
There's `1em` padding on the top, left, and right of the editor container that doesn't seem to be show in your picture. Is the picture how you want it or how it loaded in your app (if it's the latter, then there may be a bug with loading)? I'll remove the padding on the left and right. The top is blended with the theme and I think it helps improve usability.

I think the width of the line number container (class `.line-number`) is calculated automatically depending on the font size, and by default it's wide enough to hold up to 5 digits before it starts resizing itself. I'm hesitant to force a restriction of it because it may disrupt use of the editor for long notes. When you get to 100+ lines, the left indent feels very comfortable. VS Code also has a big indent near the top where the line numbers are in the single and double digits.

**Comment by atmoio** [comment]
The attached picture is as it loaded for me..

**Comment by theodorechu** [comment]
OK. Maybe the 1em top padding is there and I just can't tell in the photo. How does the indentation look now (as in beta2) with the left and right padding removed from the parent container?

**Comment by theodorechu** [comment]
I think this has been fixed.
Before:
![image](https://user-images.githubusercontent.com/3277844/104471515-9215a900-5580-11eb-978d-843fdceae4e1.png)
After:
![image](https://user-images.githubusercontent.com/22967798/104782574-4823f300-5739-11eb-8ae1-a21d024c68b3.png)
