### ISSUE TITLE
Issues with changing external themes

### ISSUE THREAD

**Issue by atmoio** [standardnotes/code-pro#5]
I'm having an issue where changing the external SN theme is not changing the background color of the text area, but it does change correctly other areas.

<img width="986" alt="Screen Shot 2021-01-14 at 7 02 19 AM" src="https://user-images.githubusercontent.com/3277844/104594238-7c62bb00-5636-11eb-8a63-2296e3c2cdcc.png">

**Comment by theodorechu** [comment]
Yeah, currently, you have you have to click the window icon to refresh the colors since the colors are set using JS through the Monaco Editor API and not by CSS. The JS reads the CSS variables and sets the theme rather than having the theme rely directly on CSS. I can set some of the colors (e.g., background and foreground as in) to change automatically as in beta1, but I haven't found the CSS selectors for things like background of the minimap. I can continue looking if you prefer the CSS approach and think the JS approach is too troublesome for users, but I think it's much easier to (for us) to use the API. To make the editor automatically refresh, I could try adding a throttled function/loop to check whether some of the key style kit variables have changed and then refresh the editor if they did. Alternatively, we could add a way for the EditorKit to recognize that the theme has changed, and then trigger the refresh when that happens. This may be preferred in case the theme changed was No Distraction and we want to automatically resize the editor to be full screen, but we may be able to detect changes in the window size in other ways. What do you think?

**Comment by atmoio** [comment]
Oof, that's a thick paragraph 😅 Hard for me to follow as I'm not overly familiar with the project architecture. Could you either simplify the paragraph structure to provide numbered options? Otherwise I trust you will find the best solution.

**Comment by theodorechu** [comment]
I fixed the issue with background color not matching the theme when switching the theme in the commit above with just CSS. The color of the minimap will not change immediately, but almost everything else will change. When you click the editor, the background of the minimap will update.
